version: "3.8"
services:
  feed-mediator:
    build: ./feed-mediator
    env_file: ./feed-mediator/.env
    restart: unless-stopped
    depends_on: [iti-mediator]

  iti-mediator:
    build: ./iti-mediator
    env_file: ./iti-mediator/.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  proxy-mediator:
    build: ./proxy-mediator
    env_file: ./proxy-mediator/.env
    ports:
      - "7000:7000"
    restart: unless-stopped

networks:
  default:
    name: lacpass-himnet
