version: "3.8"

services:

  feed-mediator:
    build: ./feed-mediator
    env_file: ./.env
    restart: unless-stopped

  fhir-forwarder-ips-mediator:
    build: ./fhir-forwarder-ips-mediator
    env_file: ./.env
    ports:
      - "8003:8003"
    restart: unless-stopped

  fhir-proxy-mediator:
    build: ./fhir-proxy-mediator
    env_file: ./.env
    ports:
      - "7000:7000"
    restart: unless-stopped

  lacpass-iti65-mediator:
    build: ./lacpass-iti65
    env_file: ./.env
    # Ajusta el mapeo de puertos según el puerto que exponga tu mediador ITI‑65
    ports:
      - "8005:8005"
    #volumes:
    #  - ./tmp:/tmp
    tmpfs:
      - /tmp:size=64m,mode=1777
    restart: unless-stopped

  lacpass-iti67-68-mediator:
    build: ./lacpass-iti67-68
    env_file: ./.env
    # Ajusta el mapeo de puertos según el puerto que exponga tu mediador ITI‑67/68
    ports:
      - "8006:8006"
    restart: unless-stopped

  lacpass-iti78-mediator:
    build: ./PDQm Mediator
    env_file: ./.env
    # Ajusta el mapeo de puertos según el puerto que exponga tu mediador ITI‑67/68
    ports:
      - "8007:8007"
    restart: unless-stopped

  vhl-mediator:
    build: ./VHL-Mediator
    env_file: ./.env
    # Ajusta el mapeo de puertos según el puerto que exponga tu mediador ITI‑67/68
    ports:
      - "8008:8008"
    restart: unless-stopped

  fhir-forwarder-inmunization-mediator:
    build: ./fhir-forwarder-inmunization-mediator
    env_file: ./.env
    ports:
      - "8009:8009"
    restart: unless-stopped
  
  fhir-forwarder-medicationrequest-mediator:
    build: ./fhir-forwarder-medicationrequest-mediator
    env_file: ./.env
    ports:
      - "8010:8010"
    restart: unless-stopped

networks:
  default:
    name: lacpass-himnet
